# travisci continuous integration config file.

language: python
python:
  #- "2.5"
  #- "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# command to install
install:
#  - pip install . --use-mirrors
#  - pip install -r requirements.txt --use-mirrors
  - python config.py -auto
  - python setup.py install -noheaders

env:
  - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk

# command to run tests
script: 
  - python -m pygame.tests.__main__ --exclude opengl


# Here we install the ubuntu dependencies with apt-get.
before_install:
  - sudo apt-get update
  - sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev python-numpy libportmidi-dev libjpeg-dev libtiff4-dev libx11-6 libX11-dev xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic

# Here we can notify the pygame irc chat.

#notifications:
#  irc:
#    channels: "irc.freenode.org#pygame"
#    on_success: change
#    on_failure: change
