environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
    DISTRIBUTIONS: "bdist_wheel"
    PYGAME_USE_PREBUILT: "1"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.11"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "%WITH_COMPILER% %PYTHON%/python config.py -auto"
  - "%WITH_COMPILER% %PYTHON%/python setup.py build"
  - "%WITH_COMPILER% %PYTHON%/python setup.py -setuptools %DISTRIBUTIONS%"
  - ps: "ls dist"

  # Install the wheel to test it
  - "%PYTHON%/python -m pip install --pre --no-index --find-links dist/ pygame"

# Appveyor's build step is specific to .NET projects, so we build in the
# install step instead.
build: off

test_script:
  - "mkdir empty_folder"
  - "cd empty_folder"
  - "%PYTHON%/python -m pygame.tests"

  # Move back to the project folder
  - "cd .."

artifacts:
  - path: dist\*

