contact_links:
  - name: ğŸ“š Documentation
    url: https://www.pygame.org/docs/
    about: "If you have a question, please try the documentation first."
  - name: â“ Discord
    url: https://discord.gg/r8yreB6
    about: "If you can't find the answers you are looking for on the website, try our community Discord."